A whole bunch more cosmetic fixes and removal of unnecessary code.
 - Rename arch/Config_new.pl -> arch/Config.pl (there's no "old" config
   stuff anymore)
 - Remove all WRF_*_CORE-related environment variables; they are unnecessary
 - Remove compile script language to automatically try to configure if
   it has not yet been done: we always want the user to run ./configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,7 +8,6 @@ FORTRAN_COMPILER_TIMER=""
 opt_level="-f"
 print_usage=""
 chemistry=""
-wrf_core=""
 while [ $# -ge 1 ]; do
     case $1 in
       -d) opt_level="-d" ;;
@@ -19,10 +18,6 @@ while [ $# -ge 1 ]; do
       -os) shift ; WRF_OS=$1 ;;
       -mach) shift ; WRF_MACH=$1 ;;
       -time) shift ; FORTRAN_COMPILER_TIMER=$1 ;;
-      arw) wrf_core=EM_CORE  ;;
-      nmm) wrf_core=NMM_CORE  ;;
-      coamps) wrf_core=COAMPS_CORE  ;;
-      exp) wrf_core=EXP_CORE  ;;
     esac
     shift
 done
@@ -331,10 +326,9 @@ fi
 if test -n "$PERL" ; then
    srch=`grep -i "^#ARCH.*$os" arch/configure_new.defaults | grep -i "$mach"`
    if [ -n "$srch" ] ; then
-     $PERL arch/Config_new.pl -dmparallel=$COMMLIB -ompparallel=$OMP -perl=$PERL \
+     $PERL arch/Config.pl -dmparallel=$COMMLIB -ompparallel=$OMP -perl=$PERL \
           -netcdf=$NETCDF -pnetcdf=$PNETCDF -phdf5=$PHDF5 -os=$os -mach=$mach -ldflags=$ldflags \
-          -compileflags=$compileflags -opt_level=$opt_level -USENETCDFF=$USENETCDFF -time=$FORTRAN_COMPILER_TIMER \
-          -wrf_core=$wrf_core
+          -compileflags=$compileflags -opt_level=$opt_level -USENETCDFF=$USENETCDFF -time=$FORTRAN_COMPILER_TIMER 
      if test ! -f configure.gen_be ; then
        exit 1
      fi
@@ -345,14 +339,8 @@ if test -n "$PERL" ; then
    else
      WRF_OS=$os ; export WRF_OS
      WRF_MACH=$mach ; export WRF_MACH
-     echo '*** Configuration not found in configure_new.defaults; checking configure_old.defaults ***'
-
-     # see if we still have an old setting laying around from v2
-     if [ "$opt_level" = "-d" ] ; then
-       arch/config_old $opt_level 
-     else
-       arch/config_old
-     fi
+     echo '*** Configuration not found in configure_new.defaults***'
+     exit 2
 
    fi
 fi
